import pandas as pd
import numpy as np

configfile: "../config/config.yaml"

samples_df = pd.read_csv(config["misc"]["samples_csv"])
sample_names = samples_df["sample_name"]
subsampling_iterations = range(1, config["multik"]["subsampling_iterations"] + 1)
min_leiden_res = config["multik"]["min_leiden_res"]
max_leiden_res = config["multik"]["max_leiden_res"]
leiden_res_step = config["multik"]["leiden_res_step"]
leiden_resolutions = ["{:.2f}".format(i) for i in np.arange(min_leiden_res, max_leiden_res + leiden_res_step, leiden_res_step)]

include: "rules/aa_preprocessing.smk"
include: "rules/ba_clustering.smk"
include: "rules/ca_dge.smk"
include: "rules/da_multik.smk"

rule workflow:
    input:
        expand(rules.preprocessing.output, sample_name=sample_names),
        expand(rules.clustering.output, sample_name=sample_names),
        expand(rules.dge.output, sample_name=sample_names),
        expand(rules.multik_compute.output, sample_name=sample_names, subsampling_iteration=subsampling_iterations, leiden_resolution=leiden_resolutions),
        expand(rules.multik_collect.output, sample_name=sample_names)
