shared:
  samples_csv: "../resources/samples.csv" # (str) Recapitulative samples table, must have two columns: "sample_name","matrix_name"
  plot_ext: "svg" # (str) Can be either one of: "png", "jpg", "jpeg", "svg", "pdf", "eps", "tif", "tiff"

preprocessing:

clustering:

dge:
